version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: nfl-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nfl-own-your-team
    volumes:
      - mongodb_data:/data/db
    networks:
      - nfl-network

networks:
  nfl-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
